name: .NET Console App CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Install pre-commit dependencies
      run: pip install pre-commit

    - name: Run pre-commit hooks
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files
        continue-on-error: false

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Console App
      run: dotnet build --no-restore --configuration Release

    - name: Collect Code Coverage
      run: dotnet test --no-build --configuration Release
